In [1]:
import pandas as pd

In [26]:
df1 = pd.read_excel("Premium_Metrics_202550.xlsx")

In [15]:
df1

   Function                          Metric  202550 vs Baseline vs Last week
0   PREMIUM                            Base  523.8K          9%           2%
1       NaN                 MAC (% of Base)     35%        -285         -127
2       NaN                      Weekly TPC    2.15         712         -389
3       NaN                      Weekly SPC   12.3K         -2%         -55%
4       NaN                       GMV Share    5.2%        -178         -524
5   classoc                      Unit share   1.35%         -15          -19
6       NaN                    %Visit share   0.53%           5           -1
7       NaN                  New Activation    2.1K         92%      -21.45%
8       NaN                           Churn    3.2K     -28.73%      -72.18%
9       NaN  Supercoin balance( Liquidity )    102M         14%       -0.98%
10      NaN                 Program Cost 1P    7.5M     -51.23%      -42.65%
11  classic                            Base  523.8K        0.09         0.02
12      NaN                 MAC (% of Base)    0.35        -285         -127
13      NaN                      Weekly TPC    2.15         712         -389
14  PREMIUM                      Weekly SPC   12.3K       -0.02        -0.55
15      NaN                       GMV Share   0.052        -178         -524
16      NaN                      Unit share  0.0135         -15          -19
17      NaN                    %Visit share  0.0053           5           -1
18      NaN                  New Activation    2.1K        0.92      -0.2145
19  classoc                           Churn    3.2K     -0.2873      -0.7218
20      NaN  Supercoin balance( Liquidity )    102M        0.14      -0.0098
21      NaN                 Program Cost 1P    7.5M     -0.5123      -0.4265

In [16]:
df1["Function"] = df1["Function"].ffill()

In [17]:
df1

   Function                          Metric  202550 vs Baseline vs Last week
0   PREMIUM                            Base  523.8K          9%           2%
1   PREMIUM                 MAC (% of Base)     35%        -285         -127
2   PREMIUM                      Weekly TPC    2.15         712         -389
3   PREMIUM                      Weekly SPC   12.3K         -2%         -55%
4   PREMIUM                       GMV Share    5.2%        -178         -524
5   classoc                      Unit share   1.35%         -15          -19
6   classoc                    %Visit share   0.53%           5           -1
7   classoc                  New Activation    2.1K         92%      -21.45%
8   classoc                           Churn    3.2K     -28.73%      -72.18%
9   classoc  Supercoin balance( Liquidity )    102M         14%       -0.98%
10  classoc                 Program Cost 1P    7.5M     -51.23%      -42.65%
11  classic                            Base  523.8K        0.09         0.02
12  classic                 MAC (% of Base)    0.35        -285         -127
13  classic                      Weekly TPC    2.15         712         -389
14  PREMIUM                      Weekly SPC   12.3K       -0.02        -0.55
15  PREMIUM                       GMV Share   0.052        -178         -524
16  PREMIUM                      Unit share  0.0135         -15          -19
17  PREMIUM                    %Visit share  0.0053           5           -1
18  PREMIUM                  New Activation    2.1K        0.92      -0.2145
19  classoc                           Churn    3.2K     -0.2873      -0.7218
20  classoc  Supercoin balance( Liquidity )    102M        0.14      -0.0098
21  classoc                 Program Cost 1P    7.5M     -0.5123      -0.4265

In [27]:
md_blocks = []

for function, g in df1.groupby("Function"):
    md = f"## {function}\n\n"
    md += g.drop(columns=["Function"]).to_markdown(index=False)
    md_blocks.append(md)

markdown_output = "\n\n".join(md_blocks)

In [28]:
print(markdown_output)

## PREMIUM

| Metric     | 202551   | 202550   | vs Baseline   | vs Last week   |
|:-----------|:---------|:---------|:--------------|:---------------|
| Base       | 523.8K   | 523.8K   | 9%            | 2%             |
| Weekly SPC | 12.3K    | 12.3K    | -0.02         | -0.55          |

## classic

| Metric   | 202551   | 202550   |   vs Baseline |   vs Last week |
|:---------|:---------|:---------|--------------:|---------------:|
| Base     | 523.8K   | 523.8K   |          0.09 |           0.02 |

## classoc

| Metric     | 202551   | 202550   |   vs Baseline |   vs Last week |
|:-----------|:---------|:---------|--------------:|---------------:|
| Unit share | 1.35%    | 1.35%    |      -15      |       -19      |
| Churn      | 3.2K     | 3.2K     |       -0.2873 |        -0.7218 |

In [40]:
import gspread
import pandas as pd

gc = gspread.service_account(
    filename="service-account-482606-599a3bb67591.json"
)

sh = gc.open("wbr")
ws = sh.worksheet("new1")

data = ws.get_all_values()
df = pd.DataFrame(data[1:], columns=data[0])

print(df)

   Function                          Metric  202551  202550 vs Baseline  \
0   PREMIUM                            Base  523.8K  523.8K          9%
1                           MAC (% of Base)     35%     35%        -285
2                                Weekly TPC    2.15    2.15         712
3                                Weekly SPC   12.3K   12.3K         -2%
4                                 GMV Share   5.20%   5.20%        -178
5   classoc                      Unit share   1.35%   1.35%         -15
6                              %Visit share   0.53%   0.53%           5
7                            New Activation    2.1K    2.1K         92%
8                                     Churn    3.2K    3.2K     -28.73%
9            Supercoin balance( Liquidity )    102M    102M         14%
10                          Program Cost 1P    7.5M    7.5M     -51.23%
11  classic                            Base  523.8K  523.8K        0.09
12                          MAC (% of Base)    0.35    0.35        -285
13                               Weekly TPC    2.15    2.15         712
14  PREMIUM                      Weekly SPC   12.3K   12.3K       -0.02
15                                GMV Share   0.052   0.052        -178
16                               Unit share  0.0135  0.0135         -15
17                             %Visit share  0.0053  0.0053           5
18                           New Activation    2.1K    2.1K        0.92
19  classoc                           Churn    3.2K    3.2K     -0.2873
20           Supercoin balance( Liquidity )    102M    102M        0.14
21                          Program Cost 1P    7.5M    7.5M     -0.5123

   vs Last week
0            2%
1          -127
2          -389
3          -55%
4          -524
5           -19
6            -1
7       -21.45%
8       -72.18%
9        -0.98%
10      -42.65%
11         0.02
12         -127
13         -389
14        -0.55
15         -524
16          -19
17           -1
18      -0.2145
19      -0.7218
20      -0.0098
21      -0.4265